apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: advisor-db-pvc
  namespacee: premerge-advisor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
