{
 "title": "LLVM",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "LLVM Premerge check status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1-llvm_premerge_checks_premerge_checks_linux_status",
     "legendFormat": "Linux Status"
    },
    {
     "expr": "1-llvm_premerge_checks_premerge_checks_windows_status",
     "legendFormat": "Windows Status"
    }
   ]
  },
  {
   "title": "% Linux workflow completed under X over the last 7 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    < 50)\n)[7d:])\n\n/\n\nsum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    )\n)[7d:])",
     "legendFormat": "<50mn"
    },
    {
     "expr": "sum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    < 60)\n)[7d:])\n\n/\n\nsum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    )\n)[7d:])",
     "legendFormat": "<1h"
    },
    {
     "expr": "sum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    < 90)\n)[7d:])\n\n/\n\nsum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    )\n)[7d:])",
     "legendFormat": "<1h30"
    }
   ]
  },
  {
   "title": "% Windows workflow completed under X over the last 7 days",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_windows_run_time + llvm_premerge_checks_premerge_checks_windows_queue_time) / 60)\n    < 50)\n)[7d:])\n\n/\n\nsum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_windows_run_time + llvm_premerge_checks_premerge_checks_windows_queue_time) / 60)\n    )\n)[7d:])",
     "legendFormat": "<50mn"
    },
    {
     "expr": "sum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    < 60)\n)[7d:])\n\n/\n\nsum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    )\n)[7d:])",
     "legendFormat": "<1h"
    },
    {
     "expr": "sum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    < 90)\n)[7d:])\n\n/\n\nsum_over_time((\n    count(\n    ((llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60)\n    )\n)[7d:])",
     "legendFormat": "<1h30"
    }
   ]
  },
  {
   "title": "Workflow duration (queue+run)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "(llvm_premerge_checks_premerge_checks_linux_run_time + llvm_premerge_checks_premerge_checks_linux_queue_time) / 60",
     "legendFormat": "Linux"
    },
    {
     "expr": "(llvm_premerge_checks_premerge_checks_windows_run_time + llvm_premerge_checks_premerge_checks_windows_queue_time) / 60",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "Queued & running job count (Linux)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Workflows" } },
   "targets": [
    {
     "expr": "running_workflow_count_premerge_checks_linux",
     "legendFormat": "Running workflow count"
    },
    {
     "expr": "workflow_queue_size_premerge_checks_linux",
     "legendFormat": "Queued workflow count"
    }
   ]
  },
  {
   "title": "Queued & running job count (Windows)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Workflows" } },
   "targets": [
    {
     "expr": "running_workflow_count_premerge_checks_windows",
     "legendFormat": "Running workflow count"
    },
    {
     "expr": "workflow_queue_size_premerge_checks_windows",
     "legendFormat": "Queued workflow count"
    }
   ]
  },
  {
   "title": "Linux - Autoscale node count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Instances" } },
   "targets": [
    {
     "expr": "floor(sum(kube_node_status_capacity{cluster=\"llvm-premerge-prototype\", node=~\"gke-llvm-premerge-pr-llvm-premerge-li-.*\", resource=\"cpu\"}) / 64)",
     "legendFormat": "Node count"
    }
   ]
  },
  {
   "title": "Windows - Autoscale node count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Instances" } },
   "targets": [
    {
     "expr": "floor(sum(kube_node_status_capacity{cluster=\"llvm-premerge-prototype\", node=~\"gke-72ba39-.*\", resource=\"cpu\"}) / 64)",
     "legendFormat": "Node count"
    }
   ]
  },
  {
   "title": "Premerge checks queue time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "floor(llvm_premerge_checks_premerge_checks_linux_queue_time / 60) ",
     "legendFormat": "Linux"
    },
    {
     "expr": "floor(llvm_premerge_checks_premerge_checks_windows_queue_time / 60) ",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "Premerge checks run time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "floor(llvm_premerge_checks_premerge_checks_linux_run_time / 60)",
     "legendFormat": "Linux"
    },
    {
     "expr": "floor(llvm_premerge_checks_premerge_checks_windows_run_time / 60)",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(max by (cluster, node) (kube_node_status_capacity{cluster=\"llvm-premerge-prototype\", resource=\"cpu\"}))",
     "legendFormat": "Physical capacity of cluster"
    },
    {
     "expr": "sum(max by (cluster, node, namespace, pod, container, resource) (kube_pod_container_resource_limits{container!=\"\", resource=~\"cpu\", cluster=~\"llvm-premerge-prototype\"}))",
     "legendFormat": "Sum of container CPU limits"
    },
    {
     "expr": "sum(max by (cluster, node, namespace, pod, container, resource) (kube_pod_container_resource_requests{container!=\"\", resource=~\"cpu\", cluster=~\"llvm-premerge-prototype\"}))",
     "legendFormat": "Sum of container CPU requests"
    },
    {
     "expr": "sum(1-max by (cluster, instance, cpu, core) (rate(node_cpu_seconds_total{cluster=\"llvm-premerge-prototype\", mode=\"idle\"}[$__rate_interval]))) >= 0",
     "legendFormat": "Cluster CPU usage"
    }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (cluster, node) (kube_node_status_capacity{cluster=\"llvm-premerge-prototype\", resource=\"memory\"}))",
     "legendFormat": "Physical capacity of cluster"
    },
    {
     "expr": "sum(max by (cluster, node, namespace, pod, container, resource) (kube_pod_container_resource_limits{container!=\"\", resource=~\"memory\", cluster=~\"llvm-premerge-prototype\"}))",
     "legendFormat": "Sum of container memory limits"
    },
    {
     "expr": "sum(max by (cluster, node, namespace, pod, container, resource) (kube_pod_container_resource_requests{container!=\"\", resource=~\"memory\", cluster=~\"llvm-premerge-prototype\"}))",
     "legendFormat": "Sum of container memory requests"
    },
    {
     "expr": "\n      sum(\n        max by (cluster, node) (kube_node_status_capacity{cluster=\"llvm-premerge-prototype\", resource=\"memory\"})\n        - on (cluster, node) group_left\n        max by (cluster, node) (\n          label_replace(\n            windows_memory_available_bytes{cluster=\"llvm-premerge-prototype\"}\n            OR\n            node_memory_MemAvailable_bytes{cluster=\"llvm-premerge-prototype\"}\n            , \"node\", \"$1\", \"instance\", \"([^:]+).*\"\n          )\n        )\n      )\n    ",
     "legendFormat": "Cluster memory usage"
    }
   ]
  }
 ]
}