githubConfigUrl: "https://github.com/llvm"
githubConfigSecret: "github-token"

minRunners: 0
maxRunners: 16

runnerGroup: ${ runner_group_name }

template:
  metadata:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  spec:
    serviceAccountName: windows-runners-ksa
    tolerations:
    - key: "node.kubernetes.io/os"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
    - key: "premerge-platform"
      operator: "Equal"
      value: "windows-2022"
      effect: "NoSchedule"
    nodeSelector:
      premerge-platform: windows-2022
    containers:
      - name: runner
        resources:
          requests:
            cpu: 28
        image: ghcr.io/llvm/ci-windows-2022:latest
        command: ["run.cmd"]
        args: ["--jitconfig", "$(ACTIONS_RUNNER_INPUT_JITCONFIG)"]
        env:
          - name: DISABLE_RUNNER_UPDATE
            value: "true"
          # We pass the GCS bucket name in as an environment variable as it is
          # different per cluster. We do not directly pass this to sccache
          # through the SCCACHE_GCS_BUCKET variable so that we can control how
          # sccache is caching directly in the workflow.
          - name: CACHE_GCS_BUCKET
            value: ${ cache_gcs_bucket }
        # Add a volume/mount it to C:/_work so that we can use more than 20GB
        # of space. Windows containers default to only having 20GB of scratch
        # space and there is no way to configure this through kubernetes
        # although the underlying containerd runtime should support it. So
        # instead we just use a emptyDir volume mounted at C:/_work, which is
        # where the GHA runner does everything.
        volumeMounts:
          - name: builddir
            mountPath: "C:/_work"
    volumes:
      - name: builddir
        emptyDir: {}

