apiVersion: batch/v1
kind: CronJob
metadata:
  name: amend-pull-request-data-cronjob
  namespace: operational-metrics
spec:
  # Every 2 hours
  # Frequency must match that of amend_pull_request_data.py
  schedule: "0 */2 * * *"
  timeZone: "Etc/UTC"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: operational-metrics-ksa
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: "true"
          containers:
          - name: amend-pull-request-data
            image: ghcr.io/llvm/operations-metrics:latest
            command: ["python3", "amend_pull_request_data.py"]
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: operational-metrics-secrets
                  key: github-token
            resources:
              requests:
                cpu: "250m"
                # We explicitly use Mi here instead of a decimal number of
                # Gi because k8s will automatically convert to Mi which
                # terraform then thinks differs from what it intended to apply.
                memory: "512Mi"
              limits:
                cpu: "2"
                memory: "2Gi"
          restartPolicy: OnFailure
