apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazel-fixer-bot
  namespace: bazel-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazel-fixer-bot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  template:
    metadata:
      labels:
        app: bazel-fixer-bot
    spec:
      serviceAccountName: bazel-cache-ksa
      containers:
        - name: runner
          image: ghcr.io/llvm/bazel-fixer-bot:latest
          command: [".venv/bin/python3"]
          args: ["./bazelbot_server.py", "--llvm_git_repo=/var/lib/buildkite-agent/llvm-project-bazelbot/", "--create_prs"]
          resources:
            limits:
              cpu: "60"
              memory: 230Gi
            requests:
              cpu: "60"
              memory: 230Gi
          volumeMounts:
            - name: scratch-volume
              mountPath: /dev/shm
          env:
            # TODO(boomanaiden154): We should eventually remove this token and
            # replace any such usage with the Github App.
            - name: GITHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-api-token
                  key: token
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: id
            - name: GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github-app
                  key: private-key
            - name: GITHUB_PR_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github-pr-app
                  key: id
            - name: GITHUB_PR_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: github-pr-app
                  key: private-key
            - name: GITHUB_FORK_USER
              value: google-bazel-bot
            - name: GITHUB_PR_USER
              value: llvm
            - name: GOOGLE_GENAI_USE_VERTEXAI
              value: "1"
            - name: GOOGLE_CLOUD_PROJECT
              value: "llvm-bazel"
            - name: GOOGLE_CLOUD_LOCATION
              value: "global"
            - name: POD_NAME
              value: "dummy"
      volumes:
        - name: scratch-volume
          emptyDir:
            medium: Memory
      terminationGracePeriodSeconds: 30
