#!/usr/bin/env python3
import os
import pathlib
import shutil
import subprocess
import sys

# Note:
# * Builders always use the latest version of this script, checking out the
# llvm-zorg repository. This means you can't rely on the script being updated
# in lockstep with the buildmaster being re-deployed.
# * This script expects to be run from within an LLVM build directory. e.g.
# llvm-project/build/foo.
# * The approach in this script could easily be applied to other
# architectures. It may or may not make sense to generalise this script in
# order to do so. This is intentionally left for evaluation when/if someone
# applies seeks to apply the same approach on another target.


def error(message):
    print(f"!!!!!!!!!! Error: {message} !!!!!!!!!!")
    sys.exit(1)


# Validate environment variables
for var in ["BB_IMG_DIR", "BB_QEMU_CPU", "BB_QEMU_SMP", "BB_QEMU_MEM"]:
    if not os.getenv(var):
        error(f"{var} not set")

# Create ext4 filesystem containing the LLVM build directory and LLVM source
# tree. Two layouts are supported:
# 1) A typical layout used in local development, with build directories within
# build/ in the monorepo checkout.
# 2) The layout used by ClangBuilder.py in CI, with build directories as
# siblings to the monorepo checkout (named 'llvm').
print("@@@@@@@@@@ Creating ext4 filesystem with LLVM build directory @@@@@@@@")

# Find the build directory, which for 'check-all' will be cwd, but might be
# the parent for e.g. 'check-llvm-foo' which will change to build_dir/test
# before invoking lit.
build_dir = pathlib.Path.cwd()
while build_dir != build_dir.parent:  # Stop at root
    if (build_dir / '.ninja_deps').exists():
        break
    build_dir = build_dir.parent
if not (build_dir / '.ninja_deps').exists():
    error("Failed to find build directory")

current_path = pathlib.Path.cwd()
print(f"Initial working directory: {current_path}. Found build_dir: {build_dir}")

llvm_img = build_dir / "llvm-project.img"
print(f"Allocating file for filesystem image at: {llvm_img}")
subprocess.run(["fallocate", "-l", "50GiB", llvm_img], check=True)

os.chdir(build_dir)
build_dir_name = build_dir.name
target_uid = 1000
target_gid = 1000

if (build_dir.parent.parent / ".git").is_dir():
    print("Note: 'Local dev' layout detected (build/build_dir nested in LLVM checkout)")
    extra_tar_args = [
        f"--exclude=build/{p.name} "
        for p in build_dir.parent.iterdir()
        if p.is_dir() and p.name != build_dir_name
    ]
    extra_tar_args.append("--exclude=.git")
    extra_tar_args.append(f"--exclude=build/{build_dir_name}/llvm-project.img")
    paths_to_tar = "."
    change_to_dir = "../.."
    base_mount_path = build_dir.parent.parent
elif (build_dir.parent / "llvm" / ".git").is_dir():
    print("Note: 'CI style' layout detected (llvm checkout and build_dir as siblings)")
    extra_tar_args = [
        "--exclude=llvm/.git",
        f"--exclude={llvm_img.relative_to(build_dir.parent)}"
    ]
    paths_to_tar = f"llvm {build_dir_name}"
    change_to_dir = ".."
    base_mount_path = build_dir.parent
else:
    error("Unrecognized repo/build layout")

tar_command = (
    f"tar --create --file=- --owner={target_uid} --group={target_gid} "
    f"{' '.join(extra_tar_args)} "
    f"-C {change_to_dir} {paths_to_tar} | mkfs.ext4 -d - {llvm_img}"
)
print(f"About to execute tar command: {tar_command}")
subprocess.run(tar_command, shell=True, check=True)

# Create appropriate exec-on-boot script
hgcomm_path = build_dir / "hgcomm"

if hgcomm_path.exists():
    shutil.rmtree(hgcomm_path)
hgcomm_path.mkdir()

args_string = " ".join(sys.argv[1:])
exec_on_boot_content = f"""#!/bin/sh
error() {{
  printf "!!!!!!!!!! Error: %s !!!!!!!!!!\\n" "$*" >&2
  exit 1
}}
mkdir -p "{base_mount_path}" || error "Can't make mount path"
chown {target_uid}:{target_gid} "{base_mount_path}" || error "Chown failed"
mount -t ext4 /dev/vdb "{base_mount_path}" || error "Mount failed"
if [ -f "{build_dir}/tools/clang/test/lit.site.cfg.py" ]; then
  # Workaround llvm_external_lit being re-invoked by update_cc_test_checks
  # tests.
  sed -i 's/^config\\.llvm_external_lit.*$/config.llvm_external_lit = path(r"")/' "{build_dir}/tools/clang/test/lit.site.cfg.py"
fi
cd "{current_path}"
su user -c "/usr/bin/python3 {build_dir}/bin/llvm-lit {args_string}"
"""
exec_on_boot_path = hgcomm_path / "exec-on-boot"
exec_on_boot_path.write_text(exec_on_boot_content)
exec_on_boot_path.chmod(0o755)

# Launch qemu-system appliance
print("@@@@@@@@@@ Pivoting execution to qemu-system @@@@@@@@")
# fmt: off
qemu_command = [
    "qemu-system-riscv64",
    "-machine", "virt",
    "-cpu", os.getenv("BB_QEMU_CPU"),
    "-smp", os.getenv("BB_QEMU_SMP"),
    "-m", os.getenv("BB_QEMU_MEM"),
    "-device", "virtio-blk-device,drive=hd",
    "-drive", f"file={os.getenv('BB_IMG_DIR')}/rootfs.img,if=none,id=hd,format=raw",
    "-virtfs", "local,path=hgcomm,mount_tag=hgcomm,security_model=none,id=hgcomm",
    "-device", "virtio-blk-device,drive=hdb",
    "-drive", "file=llvm-project.img,format=raw,if=none,id=hdb",
    "-bios", "/usr/share/qemu/opensbi-riscv64-generic-fw_dynamic.bin",
    "-kernel", f"{os.getenv('BB_IMG_DIR')}/kernel",
    "-initrd", f"{os.getenv('BB_IMG_DIR')}/initrd",
    "-object", "rng-random,filename=/dev/urandom,id=rng",
    "-device", "virtio-rng-device,rng=rng",
    "-nographic",
    "-append", "rw quiet root=/dev/vda console=ttyS0",
]
# fmt: on
print(f"About to execute qemu command: {' '.join(qemu_command)}")
subprocess.run(qemu_command, check=True)
print("@@@@@@@@@@ qemu-system execution finished @@@@@@@@")

exit_code_file = hgcomm_path / "exec-on-boot.exitcode"
if exit_code_file.is_file():
    sys.exit(int(exit_code_file.read_text().strip()))
else:
    sys.exit(111)
