#!/usr/bin/env python

"""
Command line tool for submitting to a LNT server.

This script is explicitly designed to work with llvm/utils/NewNightlyTest.pl's
-submit-aux argument. It simply uploads the data to the server, and assumes the
server will sort out any input conversion issues.

This script should be totally free-standing; it is designed so users can svn
export it directly from the LLVM repository as part of their submission scripts.
"""

import plistlib
import sys
import urllib
import urllib2

def main():
    global opts
    from optparse import OptionParser
    parser = OptionParser("usage: %prog {nightlytest sentdata.txt}*")
    parser.add_option("", "--commit", dest="commit", type=int,
                      default=True)

    # FIXME: It would be nice to support an easy mechanism for localized
    # instances of the LNT infrastructure to default to the correct server for
    # their installation.
    parser.add_option("", "--server", dest="server", type=str,
                      default="http://llvm.org/perf/db_default/submitRun")

    opts,args = parser.parse_args()

    if not args:
        parser.error("no input files")

    for inputFile in args:
        print '%s: note: submitting %s' % (sys.argv[0], inputFile)

        # Encode the form data.
        f = open(inputFile, 'rb')
        values = { 'input_data' : f.read(),
                   'commit' : ("0","1")[not not opts.commit] }
        f.close()
        data = urllib.urlencode(values)

        # Send it off.
        response = urllib2.urlopen(urllib2.Request(opts.server, data))
        the_page = response.read()

        # FIXME: Parse results and return proper error code.
        print the_page


if __name__ == '__main__':
    main()
