set(CMAKE_AR "llvm-ar" CACHE STRING "")
set(CMAKE_RANLIB "llvm-ranlib" CACHE STRING "")

set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR ON CACHE BOOL "")
set(LLVM_USE_LINKER lld CACHE STRING "")
set(CMAKE_SYSTEM_NAME Generic CACHE STRING "")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY CACHE STRING "")

set(CMAKE_ASM_COMPILER clang CACHE STRING "")
set(CMAKE_ASM_COMPILER_TARGET arm-unknown-none-eabi CACHE STRING "")
set(CMAKE_C_COMPILER_TARGET arm-unknown-none-eabi CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET arm-unknown-none-eabi CACHE STRING "")

set(COMPILER_RT_BAREMETAL_BUILD ON CACHE BOOL "")
set(COMPILER_RT_BUILD_LIBFUZZER OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_PROFILE OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_SANITIZERS OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_XRAY OFF CACHE BOOL "")
set(COMPILER_RT_DEFAULT_TARGET_ONLY ON CACHE BOOL "")

set(LIBC_TARGET_TRIPLE arm-unknown-none-eabi CACHE STRING "")
set(LLVM_LIBC_ALL_HEADERS ON CACHE BOOL "")
set(LIBC_CONF_ERRNO_MODE LIBC_ERRNO_MODE_SHARED CACHE STRING "")

set(LIBC_TEST_HERMETIC_ONLY ON CACHE BOOL "")
set(LIBC_TEST_HERMETIC_TEST_ONLY ON CACHE BOOL "")
