name: CI Python Unit Tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    name: Check CI Python Unit Tests
    if: github.repository_owner == 'llvm'
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
        cache: 'pip'
    - name: Test Premerge Buildbot
      run: |
        python3 -m venv venv-premerge-buildbot
        source venv-premerge-buildbot/bin/activate
        pip3 install pytest==8.4.1
        pip3 install -r premerge/buildbot/requirements.lock.txt
        pytest zorg/buildbot/builders/annotated/premerge/dispatch_job_test.py
    - name: Test Premerge Advisor
      run: |
        python3 -m venv venv-premerge-advisor
        source venv-premerge-advisor/bin/activate
        pip3 install pytest==8.4.1
        pip3 install -r premerge/advisor/requirements.lock.txt
        pytest premerge/advisor/
    - name: Test Premerge Ops Container
      run: |
        python3 -m venv venv-premerge-ops-container
        source venv-premerge-ops-container/bin/activate
        pip3 install pytest==8.4.1
        pip3 install -r premerge/ops-container/requirements.lock.txt
        pytest premerge/ops-container/
    - name: Test BazelBot
      run: |
        python3 -m venv venv-bazelbot
        source venv-bazelbot/bin/activate
        pip3 install pytest==8.4.1
        pip3 install -r google-bazel-bot/bazel-bot/requirements.lock.txt
        pytest google-bazel-bot/bazel-bot/
